"""HTML report generation with embedded images."""

from __future__ import annotations

from base64 import b64encode
from html import escape
from pathlib import Path

import pandas as pd


def _embed_image(path: Path) -> str:
    suffix = path.suffix.lower().lstrip(".") or "png"
    data = b64encode(path.read_bytes()).decode("ascii")
    return f"data:image/{suffix};base64,{data}"


def write_html_report(summary: pd.DataFrame, output_dir: str | Path, images: list[tuple[str, Path]]) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    table_html = summary.round(4).to_html(index=False)
    blocks = []
    for title, image_path in images:
        blocks.append(
            "<section>"
            f"<h2>{escape(title)}</h2>"
            f"<img alt='{escape(title)}' src='{_embed_image(image_path)}' style='max-width:100%; border:1px solid #ddd; border-radius:10px;'>"
            "</section>"
        )

    html = f"""
<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <title>TCR/BCR diversity report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 40px; color: #202124; }}
    h1, h2 {{ color: #1f3b73; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }}
    th, td {{ border: 1px solid #d0d7de; padding: 8px; font-size: 14px; }}
    th {{ background: #f6f8fa; }}
    section {{ margin-bottom: 28px; }}
    code {{ background: #f6f8fa; padding: 0.1rem 0.3rem; border-radius: 4px; }}
  </style>
</head>
<body>
  <h1>TCR / BCR Diversity Analysis Report</h1>
  <p>Generated by <code>analyse.py</code>.</p>
  <h2>Summary metrics</h2>
  {table_html}
  {''.join(blocks)}
</body>
</html>
"""
    path = output_dir / "diversity_report.html"
    path.write_text(html, encoding="utf-8")
    return path
